sudo: required

services:
  - docker
  
addons:
  apt:
    packages:
      - docker-ce

jobs:
  include:
    - stage: test
      script:
        - docker run --rm $(echo $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER | tr 'A-Z' 'a-z') /bin/true
