version: '3'
services:
  php:
    image: dallasmakerspace/phrasenet:latest
    volumes:
      - /var/www/html/www
    ports:
      - "9000/tcp"
    networks:
      - internal
      - public
    deploy:
      replicas: 1
      labels:
        orbital.enable: "true"
        orbital.up: 3
        orbital.down: 1
        traefik.network: "public"
        traefik.frontend.port: "9000"
        traefik.enabled: "true"
        traefik.frontend.rule: "Host: digitalmedia.dallasmakerspace.org, digitalmedia.dms.local"
        traefik.frontend.priority: 10
    depends_on:
      - db
      - redis
      - search
    environment:
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      WEB_HOST: "${NGINX_HOST}"
      DB_HOST: db
      DB_APP_NAME: "${DB_APP_NAME}"
      DB_DATA_NAME: "${DB_DATA_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      
  search: ## sysctl -w vm.max_map_count=262144
    image: "elasticsearch:2.4"
    command: "elasticsearch -Des.cluster.name='phraseanet'"
    environment:
      node.name: "search"
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ES_PLUGIN_mandatory: analysis-icu
      ES_PLUGIN_analysis-icu: true

    networks:
      internal:
        aliases:
          - search
          - search.dms.local
     ulimits:
       memlock:
         soft: -1
         hard: -1
    deploy:
      resources
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    ports:
      - "9200/tcp"
      - "9300/tcp"
    
  db:
    image: mariadb
    ports:
      - "3306/tcp"
    networks:
      internal:
        aliases:
          - db
          - mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      # user1:pass1@db1;user2:pass2@host2
      DATABASE_USER: "${DB_USER}"
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      DATABASES: "${DB_APP_NAME},${DB_DATA_NAME}"
      
  redis:
    ports:
      - "6379/tcp"
    networks:
      internal:
        aliases:
          - redis
          - cache
    image: redis:alpine

networks:
  public:
    external:
      name: public
      
  internal:
    external:
      name: internal
