version: '3'
services:
  php:
    image: dallasmakerspace/phrasenet:latest
    volumes:
      - /var/www/html/www
    ports:
      - "9000/tcp"
    networks:
      - internal
      - public
    deploy:
      replicas: 1
      labels:
        orbital.enable: "true"
        orbital.up: 3
        orbital.down: 1
        traefik.network: "public"
        traefik.frontend.port: "9000"
        traefik.enabled: "true"
        traefik.frontend.rule: "Host: digitalmedia.dallasmakerspace.org, digitalmedia.dms.local"
        traefik.frontend.priority: 10
    depends_on:
      - db
      - redis
    environment:
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      WEB_HOST: "${NGINX_HOST}"
      DB_HOST: db
      DB_APP_NAME: "${DB_APP_NAME}"
      DB_DATA_NAME: "${DB_DATA_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      
  db:
    image: mariadb
    ports:
      - "3306/tcp"
    networks:
      internal:
        aliases:
          - db
          - mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      # user1:pass1@db1;user2:pass2@host2
      DATABASE_USER: "${DB_USER}"
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      DATABASES: "${DB_APP_NAME},${DB_DATA_NAME}"
      
  redis:
    ports:
      - "6379/tcp"
    networks:
      internal:
        aliases:
          - redis
          - cache
    image: redis:alpine

networks:
  public:
    external:
      name: public
      
  internal:
    external:
      name: internal
